# SPDX-License-Identifier: Apache-2.0
# j1939-demo: Zephyr + 自带极简 J1939 协议栈 (无第三方栈)
#
# 板级 DTS (io_edge_f407vet6) 已将 can1 配置为 250 kbps
# (恰好是 J1939/11 标准速率), 无需额外 overlay。

CONFIG_CAN=y
CONFIG_CAN_STM32_BXCAN=y

CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=1536
