# The west manifest file for Zephyr project.
#

manifest:
  defaults:
    remote: kabirz

  remotes:
    - name: zephyr_site
      url-base: https://github.com/zephyrproject-rtos
    - name: kabirz
      url-base: https://github.com/kabirz

  projects:
    - name: zephyr
      revision: 81723ec3c4d492283fd0469f8dbedcfda903535b
      path: zephyr
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - littlefs
          - mbedtls
          - mcuboot
          - tf-psa-crypto

    - name: canopen
      repo-path: canopen-zephyr
      revision: 7e0a7f10c6aeb951ea82b2458611640351f41739
      path: modules/canopen-zephyr
      submodules:
        - path: CANopenNode

    - name: hal_gigadevice
      revision: main
      path: modules/hal/gigadevice
      groups:
        - hal

  self:
    path: apps
    west-commands: scripts/west-commands.yml
