# 外部 SPI Flash 上 Secondary Slot (448KB) + Scratch (448KB) 扇区数较大
CONFIG_BOOT_MAX_IMG_SECTORS=256
CONFIG_BOOT_MAX_IMG_SECTORS_AUTO=n
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TIMER_RANDOM_GENERATOR=n
CONFIG_TEST_CSPRNG_GENERATOR=n
